options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/mrsmartservice:${SHORT_SHA}'
      - '.'

images:
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/mrsmartservice:${SHORT_SHA}'
